/*  ------------------------------------------------------
     Routine name:  my_diagram
     Description:   
     Project file:  code.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&input_0,&input_0_default,sizeof(input_0_default));
memcpy(&out_0,&out_0_default,sizeof(out_0_default));
memcpy(&state_vars->my_diagramv0_out_0_,&my_diagramv0_out_0_default,sizeof(my_diagramv0_out_0_default));
memcpy(&state_vars->my_diagramv1_out_0_,&my_diagramv1_out_0_default,sizeof(my_diagramv1_out_0_default));
memcpy(&state_vars->my_diagramv2_out_0_,&my_diagramv2_out_0_default,sizeof(my_diagramv2_out_0_default));
memcpy(&state_vars->my_diagramv3_out_0_,&my_diagramv3_out_0_default,sizeof(my_diagramv3_out_0_default));
memcpy(&state_vars->my_diagramv4_out_0_,&my_diagramv4_out_0_default,sizeof(my_diagramv4_out_0_default));
memcpy(&state_vars->my_diagramv4_out_1_,&my_diagramv4_out_1_default,sizeof(my_diagramv4_out_1_default));
memcpy(&state_vars->my_diagramv4_out_2_,&my_diagramv4_out_2_default,sizeof(my_diagramv4_out_2_default));
my_diagramv4_sinit__0:
;
pneumo_engine_init(&engine);
