/*  ------------------------------------------------------
     Routine name:  my_diagram
     Description:   
     Project file:  ciclo1.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&input_0,&input_0_default,sizeof(input_0_default));
memcpy(&out_0,&out_0_default,sizeof(out_0_default));
memcpy(&out_1,&out_1_default,sizeof(out_1_default));
memcpy(&out_2,&out_2_default,sizeof(out_2_default));
memcpy(&out_3,&out_3_default,sizeof(out_3_default));
memcpy(&out_4,&out_4_default,sizeof(out_4_default));
memcpy(&state_vars->my_diagramv0_out_0_,&my_diagramv0_out_0_default,sizeof(my_diagramv0_out_0_default));
memcpy(&state_vars->my_diagramv1_out_0_,&my_diagramv1_out_0_default,sizeof(my_diagramv1_out_0_default));
memcpy(&state_vars->my_diagramv1_out_1_,&my_diagramv1_out_1_default,sizeof(my_diagramv1_out_1_default));
memcpy(&state_vars->my_diagramv1_out_2_,&my_diagramv1_out_2_default,sizeof(my_diagramv1_out_2_default));
memcpy(&state_vars->my_diagramv1_out_3_,&my_diagramv1_out_3_default,sizeof(my_diagramv1_out_3_default));
memcpy(&state_vars->my_diagramv1_out_4_,&my_diagramv1_out_4_default,sizeof(my_diagramv1_out_4_default));
my_diagramv1_sinit__0:
;
welding_init(&engine);
